# Generated by Django 3.2.8 on 2021-10-14 01:20

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('id_folder', models.IntegerField(null=True)),
                ('id_user', models.IntegerField()),
                ('file_extension', models.CharField(max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=frontend.models.user_folder)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id_folder', models.AutoField(primary_key=True, serialize=False)),
                ('id_parent_folder', models.IntegerField(null=True)),
                ('id_user', models.IntegerField()),
                ('folder_name', models.CharField(max_length=255)),
                ('folder_route', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(default=None, null=True)),
            ],
        ),
    ]
