# Generated by Django 3.1.5 on 2021-10-12 16:28

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('id_folder', models.IntegerField(null=True)),
                ('id_user', models.IntegerField()),
                ('file_extension', models.CharField(max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=frontend.models.user_folder)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id_folder', models.AutoField(primary_key=True, serialize=False)),
                ('id_parent_folder', models.IntegerField(null=True)),
                ('id_user', models.IntegerField()),
                ('folder_name', models.CharField(max_length=255)),
                ('folder_route', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(default=None, null=True)),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.IntegerField()),
                ('a', models.CharField(max_length=30, null=True)),
                ('aa', models.CharField(max_length=30, null=True)),
                ('b', models.CharField(max_length=30, null=True)),
                ('bb', models.CharField(max_length=30, null=True)),
                ('c', models.CharField(max_length=30, null=True)),
                ('field', models.CharField(max_length=30, null=True)),
                ('field2', models.CharField(max_length=30, null=True)),
                ('field3', models.CharField(max_length=30, null=True)),
                ('field4', models.CharField(max_length=40, null=True)),
                ('field5', models.CharField(max_length=30, null=True)),
            ],
        ),
=======
>>>>>>> 77290981ce3beebf10474ea10e8bb289cad11680
    ]
