# Generated by Django 3.1.5 on 2021-08-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_test_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='a',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
