# Generated by Django 3.1.5 on 2021-08-31 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_test_a'),
        ('frontend', '0004_alter_test_id'),
    ]

    operations = [
    ]
