# Generated by Django 3.2.6 on 2021-08-31 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_test_id'),
        ('frontend', '0004_test_a'),
    ]

    operations = [
    ]
