# Generated by Django 3.1.5 on 2021-08-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_merge_20210830_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='b',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
