# Generated by Django 3.1.5 on 2021-08-31 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_test_c'),
        ('frontend', '0005_merge_0004_alter_test_id_0004_test_a'),
    ]

    operations = [
    ]
