# Generated by Django 3.1.5 on 2021-09-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20210831_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='d',
            field=models.IntegerField(default=5),
        ),
    ]
